### ISSUE TITLE
Compile Errors With Windows Native EOL

### ISSUE THREAD

**Issue by tajmone** [GrenDrake/glulx-assemble#1]
Thanks for this great tool! There was really a need for an up-to-date Glulx assembler.

On Windows, when I try to assemble the source files from the `demos` folder I get the following errors (due to native EOL being `CRLF`):

    basic.ga:61:4 unexpected character; \ only permitted at end of line
    basic.ga:61:22 unexpected character; \ only permitted at end of line
    basic.ga:61:27 unexpected character; \ only permitted at end of line
    basic.ga:61:1 expected identifier
    Errors occured during parse & build.

    minimal.ga:13:1 unknown mnemonic in
    Errors occured during parse & build.

    glk.ga:267:33 unterminated string
    Errors occured during preprocessing.

But if I convert the sources' EOL to Linux style (`LF`) these errors dissapear.

Any chance you could add support for `CRLF` too on the Windows version?

Or, should the `.ga` source files always employ `LF`? 

In this case, it might be worthy adding a `.gitattributes` setting to enforce Unix style EOLs in the demo files, as well as a notice about EOLs enforcement. The current project setting, when cloning the project locally on a Windows machine, will make Git normalize EOLs of `.ga` files to `CRLF`.

Thanks

**Comment by GrenDrake** [comment]
Definitely a bug - I don't use Windows much so it just never came up. I'll see about adding support for Windows line endings in a little bit.

**Comment by GrenDrake** [comment]
I think I've got a fix in place for it; let me know if it works for you.

**Comment by tajmone** [comment]
Thanks. 

I still get some errors, although slightly different:

```
basic.ga:61:1 unknown mnemonic odules
Errors occured during parse & build.

glk.ulx missing .end_header directive
glk.ulx missing start label
Errors occured during parse & build.

minimal.ga:13:5 unexpected character; \ only permitted at end of line
minimal.ga:13:1 unknown mnemonic y25
Errors occured during parse & build.

glk.ga:267:33 unterminated string
Errors occured during preprocessing.
```

The line numbers mentioned in the errors seems out of synch with the source (in some cases they are beyond the actual source lenght), it seems that `CRLF` line endins are affecting the internals position tracking. Also, some of the above errors don't seem to be in the source file:

- `basic.ga`:

        basic.ga:61:1 unknown mnemonic odules

    The source doesn't contain "`odules`".

- `minimal.ga`:

        minimal.ga:13:5 unexpected character; \ only permitted at end of line
        minimal.ga:13:1 unknown mnemonic y25

    Line 13 is the last line in the source and it's empty. In the source there is no reference to `y25` (or `25`).

You could just enforce usage of `LF` EOLs in `.ga` sources, but chances are that Windows users would end up inadvertently creating source files with native `CRLF` EOLs, and be confused by the error messages.

**Comment by tajmone** [comment]
By the way, if you convert the EOLs in the `.ga` sources from `LF` to `CRLF` under Linux, do you get the same errors?

I've peeked at the changes in your last commit, and it looks like it should also add `CRLF` support under other OSs.

I'm compiling using MinGW-W64's gcc 6.3.0:

    gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0

And, apart from some errors with the demo folder, the glulx-assemble is working fine when I change the sources EOLs to `LF`:

```
D:\glulx-assemble>mingw32-make
gcc assemble.o lexer.o parse_core.o parse_main.o parse_preprocess.o tokens.o labels.o opcodes.o utility.o strings.o -o glulx-assemble
gcc tests/test.o tests/utility.o utility.o -o test_utility
./test_utility
utility.c: RAN 10 TESTS; 0 FAILED
gcc tests/test.o tests/parse_core.o parse_core.o tokens.o utility.o -o test_parse_core
./test_parse_core
parse_core.c: RAN 5 TESTS; 0 FAILED
gcc tests/test.o tests/tokens.o tokens.o utility.o -o test_tokens
./test_tokens
tokens.c: RAN 16 TESTS; 0 FAILED
cd demos && mingw32-make
mingw32-make[1]: Entering directory 'D:/glulx-assemble/demos'
mingw32-make[1]: *** No rule to make target '../glulx-assemble', needed by 'minimal.ulx'.  Stop.
mingw32-make[1]: Leaving directory 'D:/glulx-assemble/demos'
makefile:13: recipe for target 'demos
```

**Comment by GrenDrake** [comment]
When you originally reported the issue I was able to duplicate it by changing the line endings to CRLF, but the latest changes completely fixed the issue for me on Linux.

That said, the errors you're seeing are quite interesting and suggest something has gone massively wrong with the build process. There shouldn't be any attempt to build "glk.ulx" at all - that's just an include file containing GLK-related .defines. Likewise for the unterminated string message - there shouldn't be any strings in glk.ga

I can look more into It on the weekend, but for the moment the only thing I can suggest would be to delete and reclone the project, unfortunately.

**Comment by tajmone** [comment]
> but for the moment the only thing I can suggest would be to delete and reclone the project, unfortunately.

I'll do that, I'll just hard reset my local copy to the upstream, recompile the binaries and see if the errors go away. In any case, when I assemble sources using `LF` EOL I'm still getting fully working Glulx files that I can open with WinGit without error.

>  There shouldn't be any attempt to build "glk.ulx" at all

I don't know why I get that error, I've written a batch that iterates through every `*.ga` file and tries to assemble it; so I'm not sure where that `glk.ulx` error comes from, but it's not the result of a direct attempt to assemble an `.ulx` file. Maybe the result of some internal problem with include directives?

Thanks a lot for your time.

**Comment by GrenDrake** [comment]
I've rewritten the file loading code so it'll hopefully work better (along with a number of other updates while I was there). I'll probably see about setting up a Windows development environment as well to try and dig up any other issues that might be lying in wait as well.

**Comment by tajmone** [comment]
Wonderful! Now I don't get any errors, regardless of the EOL in the source.

Thanks, this is a great project and a much needed one too!
