### ISSUE TITLE
Question About Syntax Elements

### ISSUE THREAD

**Issue by tajmone** [GrenDrake/glulx-assemble#2]
Hi @GrenDrake,

I'm drafting a glulx-assemble syntax definition for my editor (Sublime Text) to add syntax highlighting and other editing features. I just need to ask you some clarifications about some syntax items.

### Identifiers

I've peeked at the source files, but I'm not 100% sure about valid characters in identifiers. I gather that they can be represented by the following RegEx:

    [a-zA-Z_]+

But in the source I noticed:

```c
static int is_identifier(int ch) {
    return isalnum(ch) || ch == '.' || ch == '_';
}
```

Questions:

- Is the dot (`.`) a valid character in identifiers too? or is it just used in directives?
- So, numbers are never allowed in identifier? (i.e. not even after the first character)

### String Escapes

Again, by looking at the source it looks like the valid escape sequences inside strings are: `\\`, `\"`,  `\'` and `\n`.

- Any others which I've left out?
- Should remaining escaped be treated as "invalid escapes" (i.e, highlighted as errors)? e.g. `\t`, `\`, etc.

...

Hopefully I'll soon be able to publish on GitHub a working Alpha of the package, and eventually it might become a full fledged package shared on [Package Control]  (but right now my goal is just to be able to comfortably edit Glux assembler sources).

[Package Control]: https://packagecontrol.io/

**Comment by GrenDrake** [comment]
As a caveat, the syntax for glulx-assemble doesn't really have a design and is largely made up as I go along; it may not be entirely consistent.

Looks like identifiers can have letters, a dot, an underscore, and after the first character, numbers. Pretty sure I'd intended a dot only to start directives, but I don't have any particular urge to forbid them otherwise. Might disallow them at the start of an identifier, though, to avoid confusion with actual directives.

That looks right for the string escapes and I believe the assembler reports anything else as an error. More might be added in the future if I find I need them, though.

**Comment by tajmone** [comment]
Thanks a lot, this helped.

> As a caveat, the syntax for glulx-assemble doesn't really have a design and is largely made up as I go along; it may not be entirely consistent.

Sure, I realize it's still a WIP — but I'll try to keep up with the changes as the syntax gets more formalized. Also, the syntax definition isn't a huge one either, and updating it is not going to be a problem.

The package draft is almost ready, I just need to polish some corners and they I can share it on GitHub. I'll keep you up to date.

**Comment by tajmone** [comment]
Here's a first working draft of the syntax:

- https://github.com/tajmone/sublime-glulx

Your feedback and any suggestions are much appreciated.

**Comment by GrenDrake** [comment]
Looks fine at a quick glance, but, alas, I probably won't be able to provide any meaningful feedback since I don't use Sublime Text myself.

**Comment by tajmone** [comment]
>  I probably won't be able to provide any meaningful feedback since I don't use Sublime Text myself.

I strongly advise you to try Sublime Text, which is available for all the major OSs. Fortunately, its creators have allowed to freely try out ST without features restrictions or time limits — basically, you can take all the time you need to use it, until you're able to determine wether you like or not, and once you've reached that stage you then have to buy a license.

I think it's a good policy, for different people might require different time spans to get to know the editor (either because they can dedicate only so much time every week to play with it, or because they need to get a good feel on wether they are comfortable working with it). 

So, it should be perfectly OK if you install Sublime Text to give it a try and to get a chance to see how the Glulx package looks like.

There are so many good open source packages for ST (thousands) that you can say it's highly customizable. For example, when editing markdown I use a package that auto-genates/updates the TOC in the document every time I save:

https://packagecontrol.io/packages/MarkdownTOC

And many other useful packages.

Since I prefer to work with the same tools instead of having to learn how to use a new editor (e.g. one that ships with a specific language) I prefer to create a package for the syntaxes I work with (when the syntax is unsupported and there are no packages for it).

I love ST features like multi-cursors, fuzzy search, etc., and the fact that it's a highly performant tool. It also integrates well with Git, either by installing various Git packages, as well as working in tandem with the new sibling of ST, Sublime Merge (released in September):

https://www.sublimemerge.com/
